-- Additive migration for underwriter workflow.
-- Safe to run on existing DB; does not drop/recreate any table.

CREATE TABLE IF NOT EXISTS underwriters (
    underwriter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    department VARCHAR(255) NOT NULL,
    region VARCHAR(255) NOT NULL,
    experience_years INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_underwriter_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS underwriter_id BIGINT;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS underwriter_id BIGINT;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS subscription_id BIGINT;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS risk_score DOUBLE PRECISION;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS inspection_report CLOB;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS recommended_coverage DOUBLE PRECISION;

ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS cause_of_fire VARCHAR(500);
ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS salvage_value DOUBLE PRECISION;
ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS inspection_report CLOB;
ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS settlement_amount DOUBLE PRECISION;

ALTER TABLE policy_subscriptions ADD CONSTRAINT IF NOT EXISTS fk_subscription_underwriter
    FOREIGN KEY (underwriter_id) REFERENCES underwriters(underwriter_id);

ALTER TABLE claims ADD CONSTRAINT IF NOT EXISTS fk_claim_underwriter
    FOREIGN KEY (underwriter_id) REFERENCES underwriters(underwriter_id);

ALTER TABLE inspections ADD CONSTRAINT IF NOT EXISTS fk_inspection_subscription
    FOREIGN KEY (subscription_id) REFERENCES policy_subscriptions(subscription_id);

