-- Production-grade additive migration (safe)
-- No DROP, no DELETE, only additive operations.

-- Phase 1: Proposal expansion + payment metadata
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS construction_type VARCHAR(255);
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS roof_type VARCHAR(255);
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS number_of_floors INTEGER;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS occupancy_type VARCHAR(255);
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS manufacturing_process CLOB;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS hazardous_goods CLOB;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS previous_loss_history CLOB;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS insurance_declined_before BOOLEAN;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS property_value DOUBLE PRECISION;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS payment_received BOOLEAN DEFAULT FALSE;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS payment_date TIMESTAMP;
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS cover_note_file_name VARCHAR(500);
ALTER TABLE policy_subscriptions ADD COLUMN IF NOT EXISTS policy_document_file_name VARCHAR(500);

-- Phase 2: inspection deepening
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS fire_safety_available BOOLEAN;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS sprinkler_system BOOLEAN;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS fire_extinguishers BOOLEAN;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS distance_from_fire_station DOUBLE PRECISION;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS construction_risk DOUBLE PRECISION;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS hazard_risk DOUBLE PRECISION;
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS recommended_premium DOUBLE PRECISION;

-- Phase 8/claims structure
ALTER TABLE claims ADD COLUMN IF NOT EXISTS cause_of_fire VARCHAR(500);
ALTER TABLE claims ADD COLUMN IF NOT EXISTS fir_number VARCHAR(255);
ALTER TABLE claims ADD COLUMN IF NOT EXISTS fire_brigade_report_number VARCHAR(255);
ALTER TABLE claims ADD COLUMN IF NOT EXISTS salvage_details CLOB;

ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS fire_brigade_expenses DOUBLE PRECISION;
ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS other_insurance_details CLOB;
ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS under_insurance_detected BOOLEAN;
ALTER TABLE claim_inspections ADD COLUMN IF NOT EXISTS recommended_settlement DOUBLE PRECISION;

-- Phase 7: endorsements
CREATE TABLE IF NOT EXISTS policy_endorsements (
    endorsement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT,
    change_type VARCHAR(255),
    requested_coverage DOUBLE PRECISION,
    new_occupancy_type VARCHAR(255),
    new_hazardous_goods CLOB,
    reason CLOB,
    status VARCHAR(50),
    requested_by VARCHAR(255),
    reviewed_by VARCHAR(255),
    created_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    CONSTRAINT fk_endorsement_subscription FOREIGN KEY (subscription_id) REFERENCES policy_subscriptions(subscription_id)
);
